# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_modular_headers!

def pods

 	pod 'Alamofire'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Then'
	pod 'Action'
  	pod 'NSObject+Rx'
  	pod 'RxRelay'
  	pod 'Charts'
  	pod 'RxDataSources'


end

target 'MyExchange' do
        platform :ios, '12.2'
        pods
end

target 'MyExchangeTests' do
        platform :ios, '12.2'
        pods
        pod 'RxTest'
        pod 'RxBlocking'
        pod 'Nimble'
  		pod 'RxNimble'
		pod 'OHHTTPStubs'
  		pod 'OHHTTPStubs/Swift'
end